### ISSUE TITLE
Missing detail for arguments

### ISSUE THREAD

**Issue by gregbenz** [AdobeDocs/uxp-photoshop#110]
Issue in /src/pages/ps_reference/classes/photoshop.md

Details on arguments, such as options for BatchPlay are missing. The parameters look like they should be clickable, but no information is revealed when you click them.

**Comment by ashryanbeats** [comment]
Will assign to Barkin.

**Comment by ashryanbeats** [comment]
@chuckweger to remove the method description from this file at @baaygun 's request.

Barkin suggests to use this description instead: 
https://www.adobe.io/photoshop/uxp/ps_reference/media/advanced/batchplay/
