### ISSUE TITLE
Left-hand sidebar doesn't show all subpages

### ISSUE THREAD

**Issue by kerrishotts** [AdobeDocs/uxp-photoshop#114]
Issue in /src/pages/uxp/reference-js/Global Members/Data Transfers/index.md (and related)

I know we had this fixed at one point, but it looks broken again.

**Comment by icaraps** [comment]
Replacing spaces with `%20` in the paths introduced the regression see https://github.com/AdobeDocs/uxp-photoshop/commit/38e26e8a50ac0d5c1adabfd68353038b89588e1b
