### ISSUE TITLE
Need a more up-to-date example of manifest w/ 48x48 icons for PIP

### ISSUE THREAD

**Issue by kerrishotts** [AdobeDocs/uxp-photoshop#115]
Issue in /src/pages/guides/uxp_guide/uxp-misc/manifest-v4/index.md

Note that there's 32x32 icons here, for example.

**Comment by ashryanbeats** [comment]
@kerrishotts @chuckweger do we have a taker for this one this sprint?

**Comment by chuckweger** [comment]
Change has been made and committed to cw-fixes-sprint2
