### ISSUE TITLE
"last updated (on GitHub)" data may not work as expected

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop#116]
Example:
https://www.adobe.io/photoshop/uxp/uxp/reference-js/

I'm pretty sure this page was just updated today (Nov 5).

**Comment by icaraps** [comment]
Strange are you sure ? GitHub's commit history shows otherwise https://github.com/AdobeDocs/uxp-photoshop/commits/main/src/pages/uxp/reference-js/index.md

**Comment by ashryanbeats** [comment]
Oh, looks like I misunderstood. Thanks @icaraps !
