### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by rbgala84** [AdobeDocs/uxp-photoshop#130]
Hi,

There are several links that are not working. I.e: if you go to https://www.adobe.io/photoshop/uxp/guides, these are not working:

https://www.adobe.io/photoshop/uxp/uxp_guide/uxp-misc/file-access/
https://www.adobe.io/photoshop/uxp/uxp_guide/uxp-misc/network-io/
https://www.adobe.io/photoshop/uxp/uxp-developer-tool/
https://www.adobe.io/photoshop/uxp/uxp_guide/uxp-misc/localization-and-platforms/
https://www.adobe.io/photoshop/uxp/uxp_guide/uxp-misc/flyout-menus/

Can you please update those?

Thank you

Rafael

**Comment by kerrishotts** [comment]
I can't repro this on the site as it stands now; please double check and LMK if you're still having a problem.

**Comment by rbgala84** [comment]
Hi @kerrishotts thanks for your feedback. 

On my side, every time I try to access one of the links I get a 404, no matter the browser I use or machine

![Screen-Shot-2020-11-20-08-08-21](https://user-images.githubusercontent.com/64427902/99770740-3c84c900-2b08-11eb-9881-e24e89cc4571.png)

**Comment by chuckweger** [comment]
Hi @rbgala84. The URLs in question are erroneous. How were they obtained? For example, the correct file access URL is:
https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-misc/file-access/

Which is correctly linked from here:
https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-misc/

But the URL you posted is:
https://www.adobe.io/photoshop/uxp/uxp_guide/uxp-misc/file-access/
which is missing the /guides/ inner path.

@kerrishotts I'm wondering if this is another case of "zombie" links not being purged?

**Comment by rbgala84** [comment]
Hi @chuckweger, 

The links I've posted were coming from here:

![Screenshot 2020-11-23 at 09 48 50](https://user-images.githubusercontent.com/64427902/99943384-80c6d200-2d71-11eb-9abf-be8e6c9a83e4.png)

I've checked again, and it seems the site is now pointing to the right ones!

Thanks for fixing this
