### ISSUE TITLE
Parenthesis () needed in Nudge snippet

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#131]
Issue in /src/pages/ps_reference/classes/layer.md

In the Nudge snippet, this breaks:

```js
let percent = (v) => { _unit: "percentUnit", _value: v }
```

It should be:

```js
let percent = (v) => ({ _unit: "percentUnit", _value: v })
```

I guess the compiler treats the `{}` not as the returned object but as the elements enclosing the function's body.

**Comment by kerrishotts** [comment]
Hah -- Whoops! CC @baaygun, @chuckweger

**Comment by chuckweger** [comment]
Thanks @undavide. This is going to be fixed in sprint 3.

**Comment by kerrishotts** [comment]
Verified in PROD
