### ISSUE TITLE
Incorrect object syntax in fs.getFileForSaving() example

### ISSUE THREAD

**Issue by simonhenke** [AdobeDocs/uxp-photoshop#137]
Issue in /src/pages/uxp/reference-js/Modules/uxp/Persistent File Storage/FileSystemProvider.md

![image](https://user-images.githubusercontent.com/9335692/100363201-b0d5d580-2ffc-11eb-8469-c3a04aa4e3be.png)

Shouldn't it be `{ types : [ "txt" ]}` instead of `{ types = [ "txt" ]}`

Also, this function seems to be broke (I'm using Window 10 Pro).
No option gives me:
![image](https://user-images.githubusercontent.com/9335692/100363436-027e6000-2ffd-11eb-9ff3-8a14f227e973.png)
Also, "suggestedName" isn't listed as a property for the options parameter.

Adding the options like shown in the example results in:
![image](https://user-images.githubusercontent.com/9335692/100363539-2b065a00-2ffd-11eb-9af2-b1f3d2c3ef2e.png)

**Comment by ashryanbeats** [comment]
Doesn't look like this one made it into the most recent sprint:
https://www.adobe.io/photoshop/uxp/uxp/reference-js/Modules/uxp/Persistent%20File%20Storage/FileSystemProvider/
