### ISSUE TITLE
Missing samples?

### ISSUE THREAD

**Issue by havyk** [AdobeDocs/uxp-photoshop#147]
Issue in /src/pages/code_samples/javascript_samples/index.md

There's actually no samples here at all.  Are the samples on the way and I just found this too quickly?

**Comment by ashryanbeats** [comment]
Thanks @havyk! The samples are here:
https://github.com/AdobeDocs/uxp-photoshop-plugin-samples

They are linked from the page, but we agree that the link is easy to miss. @kerrishotts will address this soon :)
