### ISSUE TITLE
Is there any plan to support access pixels of the all layers?

### ISSUE THREAD

**Issue by haruby511** [AdobeDocs/uxp-photoshop#164]
This is a suggestion about this SDK.

I'm using my own developed CEP panels, filter plugins(C++ with C#) and Extend Scripts.
But, I think there is not ultimate way to develop an extension for PS yet. Each thing lack other things features.

1. Read/write the pixels to all layers. Only filter plugins can write the pixels but it is allowed for one layer.
2. Preview/update canvas in real time such like built-in filters. The filter plugin must be a modal and the API design only considered single threaded. Additionally, cannot execute actions on the way.
3. Load platform native module. Only filter plugin allowed. As I know, the UXP planning to support opening the filter plugin. It  should also support calling common native module to improve performance and extendibility.
4. Shortcut support. Not just opening a panel or dialog. Mapping in the preference and callback a function.
5. Calling actions faster. Finally, UXP considering about it.

**Comment by kerrishotts** [comment]
Hey there -- this type of question is better suited for the forums. We'd love it if you'd ask over there. :-) 

https://forums.creativeclouddeveloper.com/c/photoshop/uxp-plugin-api/64
