### ISSUE TITLE
Link to 'batchPlay' missing

### ISSUE THREAD

**Issue by premiereonscript** [AdobeDocs/uxp-photoshop#165]
Issue in /src/pages/ - https://www.adobe.io/photoshop/uxp/guides/ps_basics

Links occur in both the 'batchplay' and 'The Basics' sections

**Comment by ashryanbeats** [comment]
This one appears to have already been addressed. The links are working for me. I'll close the issue for now, but feel free to re-open if there still seems to be a problem.
