### ISSUE TITLE
Inaccurate example for Photoshop activeDocument setter

### ISSUE THREAD

**Issue by navanshu** [AdobeDocs/uxp-photoshop#187]
Issue in /src/pages/ps_reference/classes/photoshop.md

The set accessor is incorrect
const doc = Photoshop.activeDocument;

I am new to making adobe plugins, would defintely enjoy typescript typings for photoshop uxp it really reduces the amount spend on debugging and would definetly enjoy developing quality plugins.

**Comment by hansottowirtz** [comment]
@navanshu I generated typings from this documentation, you can check it out here: [hansottowirtz/adobe-uxp-types-crawler](https://github.com/hansottowirtz/adobe-uxp-types-crawler)

**Comment by navanshu** [comment]
thanks @hansottowirtz it would be of great help.

**Comment by heewooa** [comment]
Hi @navanshu. Thanks - this section will be updated in the coming release and will no longer have this problem.
