### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#202]
Issue in /src/pages/uxp/reference-spectrum/User Interface/sp-icon.md

Hi, it looks like the image that is on top of the page (url: `https://www.adobe.io/photoshop/uxp/uxp/reference-spectrum/User%20Interface/assets/sp-icon.png`) is missing.

![image](https://user-images.githubusercontent.com/5939127/114183597-21deaf80-9944-11eb-8dac-edd0038fe71c.png)

Thanks!

**Comment by JimaDobes** [comment]
Thanks @undavide this appears to be fixed at https://developer.adobe.com/photoshop/uxp/2022/uxp/reference-spectrum/User%20Interface/sp-icon/ If that's not the case please reopen with the related info.
