### ISSUE TITLE
sp-textfield Docs has multiple examples with un-closed tags

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#205]
Issue in /src/pages/uxp/reference-spectrum/User Interface/sp-textfield.md

All the examples in that page starting [from this point](https://www.adobe.io/photoshop/uxp/uxp/reference-spectrum/User%20Interface/sp-textfield/#variants-and-states) have a missing forward slash in the closing tag:

```html
<!-- is -->
<sp-textfield disabled placeholder="Phone Number"><sp-textfield>
<!-- should be -->
<sp-textfield disabled placeholder="Phone Number"></sp-textfield>
```

Careless copy and paste is thus severely punished 😅

**Comment by JimaDobes** [comment]
found in external dependency (see package.json "uxp-documentation": "github:adobedocs/uxp") and opened issue for this at https://github.com/AdobeDocs/uxp/issues/60
