### ISSUE TITLE
Typo in the require() statement

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#241]
Issue in /src/pages/uxp/reference-js/Modules/uxp/Persistent File Storage/localFileSystem.md

Extra `.uxp` to remove:

is: `require('uxp').uxp.storage.localFileSystem`
should be: `require('uxp').storage.localFileSystem`

**Comment by heewooa** [comment]
Hi @undavide, here is a duplicate issue: #186. Closing this one in favour of the other.
