### ISSUE TITLE
Reading files in plugin dicrectory

### ISSUE THREAD

**Issue by VildanHabibov** [AdobeDocs/uxp-photoshop#250]
My plugin contains lut files (.cube) and I used fs.readfilesync for rendering previews in panel. How to integrate reading files with out 
require('uxp').storage.localFileSystem.getFileForOpening() ?

**Comment by ErinFinnegan** [comment]
Your best bet is probably to ask about this [in the developer forums](https://forums.creativeclouddeveloper.com/).

**Comment by pklaschka** [comment]
Closing as its not necessarily an immediate issue in the documentation (I'm taking note that we should probably add some more guides around using the file system APIs, but as it stands, this issue is a question better suited for the forums, as suggested by Erin, and I'll thus close it for now)
