### ISSUE TITLE
Connect to photoshop generator

### ISSUE THREAD

**Issue by html5maker** [AdobeDocs/uxp-photoshop#265]
Is there a way to connect to Photoshop generator?
<img width="513" alt="generator" src="https://user-images.githubusercontent.com/27346151/136232370-56a92681-da3c-44f7-80fa-5d5540c37923.png">

**Comment by ErinFinnegan** [comment]
OK got it. So, at present, rendering out images is unpleasant in UXP. Pixel manipulation and layer renditions are [on the roadmap](https://discord.com/channels/716052909271285803/808851160722571264/895709942294642789), but how you'd accomplish this today is not great:

> 1. Create a new document
> 2. Copy the element(s) you want to render from the first document to the new document
> 3. Save the document to the temp folder in a PNG or JPG format (document.save lets you specify this)
> 4. Close the new document w/o saving
> 5. Read the results into the UXP plugin—plugin-temp:// has access to the temp folder.
> 6. After the process, be sure to clean up the file from the temp folder

I'm told you could theoretically hook up Generator if you wanted to try it, but please keep in mind Generator probably won't be supported in too many more versions of Photoshop:

> We don't technically support it, but there's no reason why UXP couldn't connect to the Generator port via XMLHttpRequest or Fetch.
> But the public node libraries that support generator won't work in UXP, so one would have to be comfortable using the low-level protocol.
> ...we can't assume Generator will be available long-term, so I'd not rely on putting a lot of work on making UXP & Generator talk to each other.
> For personal edification, though, it should be _possible_, just probably not _easy_.

**Comment by html5maker** [comment]
Thanks for the explanation!
Can you please provide a link to the roadmap (the one [you've provided](https://discord.com/channels/716052909271285803/808851160722571264/895709942294642789) is not a public one)?
