### ISSUE TITLE
Required option for `fileName` missing in the `getFileForSaving()` function

### ISSUE THREAD

**Issue by ashikka** [AdobeDocs/uxp-photoshop#272]
Issue in /src/pages/uxp/reference-js/Modules/uxp/Persistent File Storage/FileSystemProvider.md

The required option for fileName is not mentioned anywhere in the docs/

```js
const [file] = await fs.getFileForSaving({ types = [ "txt" ]});
if (!file) {
    // no file selected, or the user didn't want to overwrite one they did select
    return;
}
await file.write("It was a dark and stormy night");
```

If we do not pass the `fileName` option in this function we get an error as follows: 
<a href="https://ibb.co/qmGhfZP"><img src="https://i.ibb.co/XFB6gwv/Whats-App-Image-2021-10-26-at-21-15-03.jpg" alt="Whats-App-Image-2021-10-26-at-21-15-03" border="0"></a>

**Comment by pklaschka** [comment]
Fixed in https://github.com/AdobeDocs/uxp-photoshop/commit/718845c9f85bf765fecb7526efd3c0b01d112320, thank you for reporting this!
