### ISSUE TITLE
Modal execution documentation is not available

### ISSUE THREAD

**Issue by AAverin** [AdobeDocs/uxp-photoshop#274]
Issue in /src/pages/ps_reference/index.md

`https://developer-stage.adobe.com/photoshop/uxp/2022/ps_reference/media/executeasmodal/`
this link gives 404

**Comment by ErinFinnegan** [comment]
I can confirm this is true, and the page it ought to point to is here: https://github.com/AdobeDocs/uxp-photoshop/blob/main/src/pages/ps_reference/media/executeasmodal.md

**Comment by heewooa** [comment]
@AAverin, does the now public location: https://www.adobe.io/photoshop/uxp/2022/ps_reference/media/executeasmodal/ work for you?

**Comment by AAverin** [comment]
Clicking in the menu on the left sill leads to `https://developer-stage.adobe.com/photoshop/uxp/2022/ps_reference/media/executeasmodal/` that fails
