### ISSUE TITLE
404 Links

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#294]
Issue in /src/pages/guides/distribution/index.md

404 on the following:

[Packaging Your Plugin](https://developer.adobe.com/distribution/packaging-your-plugin/)
[Options for Distribution](https://developer.adobe.com/distribution/distribution-options/)
[Submission and Review](https://developer.adobe.com/distribution/submission-checklist/)
[Marketing Your Plugin](https://developer.adobe.com/distribution/marketing/)

Please note: the links in the left columns are fine, the ones on the page are 404

**Comment by JimaDobes** [comment]
These appear to be fixed and published, at https://developer.adobe.com/photoshop/uxp/2022/guides/distribution/
successfully tested both in the page and the left nav items
