### ISSUE TITLE
Issue in /src/pages/guides/how-to/index.md

### ISSUE THREAD

**Issue by MaherFa** [AdobeDocs/uxp-photoshop#300]
Issue in /src/pages/guides/how-to/index.md

sample code [here](https://developer.adobe.com/photoshop/uxp/guides/how-to/#how-to-get-notified-that-your-panel-is-opening-or-closing) have a typo, the following string is opened with double quotes and closed with a single quote. 

`console.log("panel is showing');`
should be
`console.log("panel is showing");`

**Comment by ErinFinnegan** [comment]
Thanks!
