### ISSUE TITLE
link to "execute as modal " is dead

### ISSUE THREAD

**Issue by shi-yan** [AdobeDocs/uxp-photoshop#303]
Issue in /src/pages/ps_reference/classes/document.md

the link to "execute as modal" on the above page points to https://developer.adobe.com/photoshop/uxp/2022/ps_reference/classes/media/executeAsModal

which is dead. 

the correct link https://developer.adobe.com/photoshop/uxp/2022/ps_reference/media/executeasmodal/

need to remove "classes" from the wrong link

**Comment by JimaDobes** [comment]
thanks @shi-yan this is fixed in 85e197c71b222e0438805db44edf82a97de821a1 and successfully tested here on gh-pages
