### ISSUE TITLE
Change Log not updated

### ISSUE THREAD

**Issue by DianaProbst** [AdobeDocs/uxp-photoshop#407]
**Live page link (and page section):** https://developer.adobe.com/photoshop/uxp/2022/ps_reference/changelog/
**Issue description:** The change log has not been updated for photoshop 24.3 or beta 24.4.  It's a really useful bit of navigation for me as I am waiting on some issues to be fixed.

**Comment by sujaisivanandan** [comment]
I see the latest changelog has the updates for 24.3,24.4 and 24.5
