### ISSUE TITLE
404 for links in API docs

### ISSUE THREAD

**Issue by rogemus** [AdobeDocs/uxp-photoshop#87]
Issue in /src/pages/ps_reference/media/advanced/prototype.md

After pressing any of the links for classes:

- app.Photoshop
- app.Document
- app.Layer
- app.ActionSet
- app.Action

The user is redirected to 404 page

**Comment by ashryanbeats** [comment]
Hi @rogemus! Thanks for reporting this. We'll get this taken care of.
