### ISSUE TITLE
Updating the content in the Design markdown pages

### ISSUE THREAD

**Issue by dcaiced0** [AdobeDocs/uxp-photoshop#89]

**Comment by ashryanbeats** [comment]
Including updates from content strategy

- Sentence case
- Image tags
- Tone of voice

**Comment by ashryanbeats** [comment]
Hand off to Chuck.

**Comment by kerrishotts** [comment]
@dcaiced0 Please check that your changes were deployed to production, and I can close.

**Comment by ashryanbeats** [comment]
@dcaiced0 Bumping this :)

**Comment by dcaiced0** [comment]
I found something I missed but I can add them to the next sprint, all the major updates are good. Do you know how I can make a header bigger? I am trying to make the "content" in the onboarding page a bigger type size using #### https://www.adobe.io/photoshop/uxp/design/ux-patterns/onboarding
