### ISSUE TITLE
Not working link

### ISSUE THREAD

**Issue by rogemus** [AdobeDocs/uxp-photoshop#92]
![Screenshot 2020-10-28 at 16 42 34](https://user-images.githubusercontent.com/9271549/97460009-a6acb280-193c-11eb-9388-abdd24637b92.png)
Upon entering on /src/pages/code_samples/react_samples/index.md link to react docs does not work

**Comment by kerrishotts** [comment]
Moved to Sprint 2; did not get into Sprint 1
