### ISSUE TITLE
Missing `createSessionToken()`

### ISSUE THREAD

**Issue by undavide** [AdobeDocs/uxp-photoshop#96]
Issue in `/src/pages/uxp/reference-js/Modules/uxp/Persistent File Storage/localFileSystem.md`

The `.createSessionToken()` entry is missing (this is the one that jumped out, please check if it's the only one who got away 😊). Also a few examples e.g. of file saving using the token would be helpful.

Thanks!

**Comment by kerrishotts** [comment]
Addressed by #124.
